version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'logotip4ik'
    assignees:
      - 'logotip4ik'
    commit-message:
      prefix: 'build'
      prefix-development: 'build'
      include: scope
  # Fetch and update latest `github-actions` packages
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'logotip4ik'
    assignees:
      - 'logotip4ik'
    commit-message:
      prefix: ci
      prefix-development: ci
      include: scope
